### ISSUE TITLE
Build Workflow Questions

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/jTrack#22]
Thoughts while scripting the deployment for this on `repo.wsu.edu`:

* Any issues with using `develop` instead of `dev` as the development branch? This would align with Spine and help with the reuse of the bash scripts over time.
* Can we remove the version number from the built files, similar to the Spine?
* Can we remove all built files from the repository once they're available for production use on `repo.wsu.edu`?

**Comment by jeremyfelt** [comment]
* Would consider removing `archive` and uploading zips as releases in GitHub for archived versions.
* We should determine what versioning to use - pre-release is 1.0.0, but package is 1.2.2.

**Comment by jeremyfelt** [comment]
Ok, first draft appears ready - `https://repo.wsu.edu/jtrack/develop/jtrack.1.2.2-beta.min.js`, `https://repo.wsu.edu/jtrack/1.0.0/jtrack.1.2.2-beta.min.js`, and `https://repo.wsu.edu/jtrack/1/jtrack.1.2.2-beta.min.js` are live.

Adjusting some nginx configs now for cache times.

**Comment by jeremyfelt** [comment]
Nginx rules are in place. All the basics should now be set.

**Comment by jeremyBass** [comment]
So quick notes on thie

> Any issues with using  develop  instead of  dev  as the development branch? This would align with Spine and help with the reuse of the bash scripts over time. 

The only reason I use "dev" is that it's short to type and it's habit from years of naming.


> Can we remove the version number from the built files, similar to the Spine?

Yeps

> Can we remove all built files from the repository once they're available for production use on  repo.wsu.edu ?

Not at this time, a lot of the outside tests pull from the `distro` folder in `dev` for testing purposes where building is not an option.

> Would consider removing  archive  and uploading zips as releases in GitHub for archived versions.

Yes it's intended to remove archive, just need it there for reference for a bit longer.

>We should determine what versioning to use - pre-release is 1.0.0, but package is 1.2.2.

Yeah I meant to do 1.2.2 on the release but autocomplete came in to play there.

**Comment by quantumJLBass** [comment]
All but the `distro` folder have been phased out or corrected.  In the repo distro moves to `develop` anyways so we line up with others at the moment on that front.

Closing this as we have a working model and it is stable.  If we need to we can reopen at a later point.
