### ISSUE TITLE
Default eventValue is 1

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/jTrack#52]
I'm not sure if this is intentional or not, but the `eventValue` passed for events appears to default to 1 if not specified elsewhere. I haven't poked at it too much, but as an integer is expected, it seems like it should default to `null` rather than the value checked for here: https://github.com/washingtonstateuniversity/jTrack/blob/dev/jtrack.js#L184

In the meantime, I've updated the WSUWP analytics plugin to pass `value: null` for each event to make sure none is sent.

**Comment by quantumJLBass** [comment]
Yeah the line needs to be `value : null` for sure.  

Side note, I seem to have lost setting on here, can you move the project back under me again.

**Comment by jeremyfelt** [comment]
Added a new @washingtonstateuniversity/jtrack-maintainers team and you are back. :)

**Comment by quantumJLBass** [comment]
rockin thanks
