### ISSUE TITLE
Tag next release of jTrack

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/jTrack#57]
I'd be in favor of tagging a new release this week. Does 1.2.6, 1.3.0, or something else make sense? The internal version number in the script appears to have been bumped a few times without a tagged release. I'm not sure which one is important. /cc @jeremyBass

**Comment by quantumJLBass** [comment]
I would be agree it has sat long enough in dev, 1.3.0 would be the appropriate as there was new but backward compatible enhancements.  I'll try to get around to this in a bit

**Comment by quantumJLBass** [comment]
it was `1.6.0` as it was 1.5.1 in dev.  Release complete
